name: face2face_env
channels:
dependencies:
    - python
    - pip
    - pip:
        - pandas
        - networkx
        - numpy
        - powerlaw
        - matplotlib
        - scipy
        - random
        - seaborn
        - math
        - collections
        - face2face